language: php
sudo: false
php:
  - 5.6
  - 7.0
services: redis-server
before_script:
  - pecl install pthreads
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit -c phpunit.xml.travisci
matrix:
  fast_finish: true